### ISSUE TITLE
Make it clearer that emails can be seen in RSS

### ISSUE THREAD

**Issue by slyons** [AhoyLemon/ballpit#21]
Didn't realize how many things had scraped my E-mail address until I figured out that the default e-mail settings in the profile expose it through the RSS feed. I had thought that it would just be visible to other forum users.

**Comment by AhoyLemon** [comment]
Oh! Interesting. I didn't know this either.

I think the better option would be to remove that from the RSS feed, don't see it as a requirement.

**Comment by slyons** [comment]
If you turn off "share my email with others" it removes it from the feed
entirely, but that works.
