### ISSUE TITLE
User Stats page all fucked up

### ISSUE THREAD

**Issue by AhoyLemon** [AhoyLemon/ballpit#27]
@samuwen pointed out this interface is a disaster.

https://ballp.it/index.php?action=profile;area=statistics;u=1

**Comment by AhoyLemon** [comment]
Ha! Also this thread
https://github.com/AhoyLemon/ballpit/issues/27

Get to it, Lemon

**Comment by AhoyLemon** [comment]
![image](https://cloud.githubusercontent.com/assets/3413200/26645921/5f404d08-45ff-11e7-840a-975f73d43ab2.png)

**Comment by eladavron** [comment]
I'm probably being needy, but while we're at it - can we add a "thumbs-up" count to the stats?

**Comment by AhoyLemon** [comment]
@eladavron Do you mean the number of kisses/slaps?

**Comment by eladavron** [comment]
Yeah but for bulbs, I got bulbs confused with thumbs ups

**Comment by AhoyLemon** [comment]
Well, I was able to find the kiss and slap variables in the `$context` object, but there's no variable for bulbs. Let me check with @BootsRaingear

**Comment by AhoyLemon** [comment]
Adjustments made.

![image](https://cloud.githubusercontent.com/assets/3413200/26652817/c54bcd7c-4616-11e7-8715-1c57e0fa6473.png)

**Comment by eladavron** [comment]
While you're at it, maybe add a border to the pop-up of the "modify profile" and "Action" buttons? The pop-up has the same background as the... Well... Background, and it's hard to see.

**Comment by eladavron** [comment]
A little cramped on Mobile:

![screenshot_20170531-234113](https://cloud.githubusercontent.com/assets/5508836/26653098/c1ee1d62-465a-11e7-9847-f831256f3dbb.png)

**Comment by AhoyLemon** [comment]
![image](https://cloud.githubusercontent.com/assets/3413200/26654543/d743a724-461c-11e7-99d1-7781c8c3d57c.png)

**Comment by AhoyLemon** [comment]
![image](https://cloud.githubusercontent.com/assets/3413200/26655152/29eaf64c-461f-11e7-938d-eec3b8ab842a.png)

**Comment by eladavron** [comment]
Sweet. Thanks Lemon!
