### ISSUE TITLE
Twitter adds "?s=19" to links, embed plugin doesn't like it.

### ISSUE THREAD

**Issue by eladavron** [AhoyLemon/ballpit#41]
For some reason, when you copy a link from twitter on Android, it now adds "?s=19" at the end.
The embed plugin doesn't like it and makes it seem like the tweet has been deleted.
Now sure - you **COULD** edit your post and remove it, but that's a hassle - especially on mobile.
I'd like to have twitter links automatically stripped of that "?s=19" (at least when fed to the embed) but I couldn't find where the plugin was in the code.
@AhoyLemon or @BootsRaingear, can you nudge me in the right direction?

**Comment by AhoyLemon** [comment]
Hey @eladavron 
Yeah, turns out the important piece actually wasn't in the repo. So, in [Sources/Load.php](https://github.com/AhoyLemon/ballpit/blob/master/Sources/Load.php) there's the js that brings in the tweet. I think you could safely parse out that url to snip off any query.

**Comment by AhoyLemon** [comment]
K, should be fixed.
