### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by eladavron** [AhoyLemon/ballpit#45]
Dark themes are easier on your eyes and your battery.
Can we have one please? I'd do it myself but I'm terrible at design.

**Comment by AhoyLemon** [comment]
I dunno, maybe? I played around with one the other day and it was simple, if somewhat boring.

![ballp it_index php_topic 3039 0 nexus 5x](https://user-images.githubusercontent.com/3413200/49878832-220b2680-fdee-11e8-910a-bf8e2cfba9df.png)

**Comment by AhoyLemon** [comment]
Also there's the consideration of where that setting goes in the stack. You can save `nightMode = true` client side really easily, but then you might get a flash from white to black before it picks up the value.

**Comment by AhoyLemon** [comment]
So the front end side of this is pretty easy. I set dark and light variables to a couple things, and then I cascade those off a certain rule. I'm thinking `<body class="light-mode">` or some such. That's fine, and doesn't require a whole lot of change to the CSS.

The challenge is in how to make that toggle happen. Like I said, to do that in client side JS is possible and would basically work, except it would flash colors on page load when the class was added.

We'd need to do it server side, which means a user setting. Now, SMF is super moddable, so I'm sure there's ways to add user settings, I just don't know how to do that.

**Comment by eladavron** [comment]
I need to do a deeper dive into the code, but I think the crux of it will be **either** in Load.php, in the function "loadTemplate" which seems to actually load the CSS where we can query the user settings:

```php
$context['html_headers'] .= "\n\t" . '<link rel="stylesheet" type="text/css" id="' . $sheet . '_css" href="' . $settings[$sheet_path] . '/css/' . $sheet . '.css" />';
```
**Or** in index.template.php (which is part of the theme itself), in "template_html_above()":

```php
 echo '
    <meta charset="iso-8859-1">
    <link rel="stylesheet" type="text/css" href="', $settings['theme_url'], '/css/ballpit.css?lastUpdated=2018-11-10" />';
```

Depending on where and in what context "$settings" and "$sheet" are loaded - this might be used to have the server deliver a different css depending on user settings.
I'll give it a deeper dive as soon as I get a chance.

**Comment by AhoyLemon** [comment]
It's the second example (index_template.php) that outputs, but that's not where I'd put it . I'd want to change the line [here](https://github.com/AhoyLemon/ballpit/blob/master/Themes/Giggle/index.template.php#L274)

from
```
<body>
```

to something like...

```
<body class="<?php if ($nightMode == true) { echo 'night-mode'; } else { echo 'day-mode'; } ?>
```

And that class being in the body would be able to do all the work.

The thing is in making that mode work. One option would actually be up here...

![image](https://user-images.githubusercontent.com/3413200/50061435-02fdf300-0166-11e9-9257-c1614c1317cf.png)


And use a sun/moon emoji to dictate the feature switch. That would work. But it means that clicking that button would save the value to your user settings. *That's* the part that's beyond my grasp.

**Comment by AhoyLemon** [comment]
Another option:

![image](https://user-images.githubusercontent.com/3413200/50061617-ae5b7780-0167-11e9-8467-ceb7c3696850.png)

**Comment by eladavron** [comment]
Second option seems less intrusive and saves you from having to do it live. You can just store those values along with the other user preferences.

**Comment by AhoyLemon** [comment]
Development on this feature is happening on the `darkMode` branch.
https://github.com/AhoyLemon/ballpit/tree/darkMode

**Comment by AhoyLemon** [comment]
@eladavron Is it alright if I have you test this at some point before launch?

**Comment by eladavron** [comment]
Sorry, missed this previous message.
I'm game if it's still relevant.
