### ISSUE TITLE
Links inside spoilers don't spoil themselves

### ISSUE THREAD

**Issue by djeserd** [AhoyLemon/ballpit#63]
The CSS has a rule to make links inside spoilers blur:
`span.spoiler:hover a[href] {
    color: transparent;
    text-shadow: 0 0 0.3em rgba(15, 157, 88, 0.2);
}`
But doesn't have a rule like this, to make it un-blur:
`span.spoiler.spoiled a[href] {
    color: #0f9d58;
    text-shadow: none;
}`

**Comment by AhoyLemon** [comment]
Great, thanks. I'll merge this in a bit.

**Comment by AhoyLemon** [comment]
Well, actually I'm gonna take your notes and redo 'em.
